# fly.toml app configuration file generated for green-fire-8194 on 2023-09-22T20:39:50-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-fire-8194"
primary_region = "sea"

[env]
  MONGODB_URI = "mongodb+srv://mpahal123:admin@cluster0.4yyppmb.mongodb.net/?retryWrites=true&w=majority"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
